import pyautogui as py
import time as t
t.sleep(0.5)
py.press("winleft")
t.sleep(0.5)
py.write("chrome")
t.sleep(0.5)
py.press("enter")
py.sleep(0.5)
py.hotkey("ctrl", "shift", "N")
t.sleep(0.5)
py.write("# inserir URL de email")
t.sleep(0.5)
py.press("enter")
t.sleep(0.5)
py.moveTo(48,272)
t.sleep(0.5)
py.click()
t.sleep(7.0)
py.write("prof.humbertoltoledo@gmail.com", interval=0.05)
t.sleep(4.0)
py.press("enter")
t.sleep(0.5)
py.press("tab")
py.write("Atividade 01 - ADSMA2", interval=0.05)
t.sleep(0.5)
py.press("tab")
t.sleep(0.5)
py.write("E aí professor, conseguimos!!!", interval=0.05)
t.sleep(0.5)
py.moveTo(1326,960)
t.sleep(0.5)
py.click()
py.moveTo(1012,299)
t.sleep(0.5)
py.click()
t.sleep(0.5)
py.moveTo(1225,251)
t.sleep(0.5)
py.click()
t.sleep(0.5)
py.press("enter")
t.sleep(0.5)
py.moveTo(1225,251)
t.sleep(0.5)
py.click()
t.sleep(0.5)
py.press("enter")
